# SwiftLint
excluded: # paths to ignore during linting. Takes precedence over `included`.
- build/
- .build/
- Client/Assets/Search/get_supported_locales.swift
- Client/Generated
- fastlane/
- Source/ExcludedFolder
- Source/ExcludedFile.swift
- Sync/Generated/Metrics.swift
- Storage/Generated/Metrics.swift
- ThirdParty
- Tests/UITests/
- DerivedData/
# Package.swift files need a custom header for swift-tools-version
# so must be excluded due to file_header rule
- Package.swift
- BrowserKit/Package.swift
- content-blocker-lib-ios/ContentBlockerGenerator/Package.swift
- BuildTools

included: # paths to include during linting. `--path` is ignored if present.
  - CatCafeManager
  
only_rules: # Only enforce these rules, ignore all others
  - blanket_disable_command
  - class_delegate_protocol
  - colon
  - comma
  - comment_spacing
  - compiler_protocol_init
  - computed_accessors_order
  - control_statement
  - duplicate_conditions
  - dynamic_inline
  - empty_enum_arguments
  - empty_parameters
#  - empty_parentheses_with_trailing_closure
#  - for_where
  - force_try
  - implicit_getter
  - inclusive_language
  - invalid_swiftlint_command
  - large_tuple
  - leading_whitespace
#  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_nsgeometry_functions
  - mark
  - no_space_in_method_call
  - ns_number_init_as_function_reference
  - operator_whitespace
  - orphaned_doc_comment
  - private_over_fileprivate
  - protocol_property_accessors_order
  - redundant_discardable_let
  - redundant_objc_attribute
  - redundant_optional_initialization
  - redundant_string_enum_value
  - redundant_void_return
  - return_arrow_whitespace
  - statement_position
  - switch_case_alignment
  - syntactic_sugar
  - trailing_newline
  - trailing_semicolon
#  - trailing_whitespace
  - unavailable_condition
  - unneeded_override
  - unneeded_synthesized_initializer
  - unused_optional_binding
  - unused_setter_value
  - vertical_parameter_alignment
  - vertical_whitespace
  - void_function_in_ternary
  - void_return
  - file_header
  - redundant_type_annotation
#  - attributes
  - closing_brace
  - closure_end_indentation
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - first_where
  - discouraged_assert
  - duplicate_imports
  - duplicate_enum_cases
  - last_where
  - modifier_order
  - multiline_arguments
  - opening_brace
  - overridden_super_call
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition
  - file_length
  - function_body_length
  - identifier_name
  - line_length
  - trailing_comma
  - nesting
  - type_name
  - cyclomatic_complexity

file_length: 500
function_body_length: 50
identifier_name:
  min_length: 2
  max_length: 40
large_tuple: 6
line_length:
  warning: 450
  ignores_urls: true
# statement_position:
#   statement_mode: "uncuddled_else"
trailing_comma:
  mandatory_comma: true
vertical_whitespace:
  max_empty_lines: 1
nesting:
  type_level: 4
  statement_level: 4
type_name:
  max_length: 1000
cyclomatic_complexity: 11
